import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { saveAs } from 'file-saver';

  //The proxy generated by ABP should not be used for file upload. If proxies are regenerated, the corresponding folders should be deleted.
  //This issue is discussed in the following link : https://github.com/abpframework/abp/issues/6384
  //For the moment, ABP's proxies can't handle types : IRemoteStream and IFormFile
  //This is why a new service was created to handle "Download".
  //"Upload" is handled in component.ts file.
@Injectable({
  providedIn: 'root'
})

export class DownloadService {

  public constructor(private http: HttpClient) {}

  public downloadFile(id:string):Observable<Blob> {
    return this.http.get(`https://localhost:44310/api/app/cv/${id}/cv`,{responseType: 'blob'});
  }
}
